#output: main.o
#	g++ -std=c++14 -g -Wall main.o -o output

#main.o: main.cpp
#	g++ -std=c++14 -g -Wall -c main.cpp

#clean:
#	rm *.o output

euler_8 : euler_8.hs
	ghc -o euler_8 euler_8.hs

clean_bin:
	rm *.o *.hi

clean:
	rm *.o *.hi euler_8
